#!/usr/bin/env bash

set -euo pipefail

ensure_git() {
    local url=$1
    local dir=$2

    if [[ ! -d $dir ]]; then
        git clone "$url" "$dir"
    else
        git -C "$dir" pull --rebase
    fi
}

ensure_git \
    https://github.com/junegunn/vader.vim \
    ./tests/.vim/pack/default/start/vim-vader

run_vim() {
    vim --not-a-term -N --clean -u ./tests/.vimrc "$@"
}

run_vim \
    '+Vader! tests/unit/**.vader'

run_vim \
    --cmd 'let g:envsubst_loaded = 1' \
    '+Vader! tests/integration/disable.vader'

run_vim \
    '+Vader! tests/integration/mappings-default.vader'

run_vim \
    --cmd 'let g:envsubst_no_mappings = 1' \
    '+Vader! tests/integration/mappings-disable.vader'

run_vim \
    --cmd 'let g:envsubst_trigger_next = "\<C-l>"' \
    --cmd 'let g:envsubst_trigger_prev = "\<C-h>"' \
    '+Vader! tests/integration/mappings-custom.vader'
